[gcp_service_account]
type = "service_account"
project_id = "pumpkins-tip-calculator"
private_key_id = "82e0d56cc42c616b9afa6c1a3d5069358d28de35"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDFDeslNZE4H5ET
idhig3f+wR/NNSoeC66xE/Tpe8/oe1MVipSLbGdU1HbcA1T9jN563F/hnlqanKpQ
BYqXa4FKq3K8NV1SMrBifKJxbgbR0pOyinDXbuKIZvcn2X97vnVU4q7yTgw4wFYh
qtH/QHuhCYp4lmRmLOufWW+Z53URaLGyjNUFIJJGA5eKBOIBNjlCJIaVOoV1DvYl
mOoqHhemgOOBimG2ZKR9qVIBrxAtX0rAlPtABwe9ppf1Nr1CazPd/8G8nDbI6DWU
JRqe5Pfq/4PlQYP2xv4brOJ5XBjapMfUeVcKzJc7SLdNzG0yVnt4ASQPCbAbSTJZ
7uNkZR8dAgMBAAECggEAB1ilvdEhrRU2MCOJMuECWffCswCKpaybUmQzUvoH7fud
BRZRw+Hid03lcX3ZTwuPpsZs96kS6SUyj0GpoUwDebBrGlul80DLBRzu5Gos7Gkc
kwEoxEtQvDOUfsKTx136G1RJH+TrfTkkbORkqE6z3TTRGf5HV2zQyvPHXpY7rc6n
4/TXpk3GL0aANEcnXjxYRRoF8jEcVua1pN+LRtNXnb6xDvtxCrXLR8Uof8OKTNGa
KeqEn5xPGaOtuRld3zEEuF323+vRrZhl4CfG8+Q/3fauQoZKmniENnv6hmPWe6M9
j6+nRqEabyD8XqLWM6X6tp52clbC2lyUUD2bXfLK8QKBgQDifUVxRtYFWWwmSJxf
HjHUeyuaZuCtVmKEMIumMMbB/MVXjd0AS108H7ZDhlViwCgupvmk7ULseLQbmqxR
XjJUCa9ByNA497x54yGWfLECTKYIdRUk4smYwXo+dpH9XvPSejYXcuIJX7GF8tNX
FuB6ISGJ4ozo+QQ4WbW4FkV/zQKBgQDeutIho5SoARUgVlpFtS4zHitybqBow+d0
9gBV+70Uo4tr7H/7lW3UYwmiYoOA6RmQZvd1o3qOX7cQiKJC+Crys5P6XyyqWAND
+fnWyUBFH4KcSnlRWc/nHtIcztwkfybW7BDNMrZ/sDh/2Q1gw3RKduQZ0JMuK64u
l6L1O9KskQKBgQC7c5Ti0Q7XdJBHCzeondP+GUcYTmdL70AwSgF6tcn6ydsGwNoV
oUp0NYbjUi4fQgy/t+DMeLY4AxqF8jkGSyD6Xt2XY726OIfclXi6FU9nKMsOGuE6
Gx1g+VjUk8v2WP0RyaY1OBcOTQ4fX788yClXy0330fJv65FrlgwJZR12TQKBgQDE
o6PJVyZzfSEtv49LY746GzS4frrYQ70hId8CCpLQmeMJkW8cqrygeh+TYe4/7YxI
VN+82GvnLtHsovS+s2MXizvmHAjPC402gof0/RDk9gDWA1pAXE6U+jz+ehMZlbiw
nxHmWBOPgAEhvnt1JpqQ845GzEJkzOOm9vFEGWDSQQKBgGzDtBjkTjhSmk8ECb7R
NnoekjtTmAnHcYKGYmLG12KuTJWv+shD6qSAzmrqK3zonF2/Z7lAGk/TlHJZVa3B
rinZsc0S3sBY/7JIo1kugPcE/oK79E6ppJiuYZNC2MvFLCHbDRHymd5Uy5F78NgF
I64qdzXWr167+2z8ER4ByMiB
-----END PRIVATE KEY-----
"""
client_email = "pumpkins-tip-calculator@pumpkins-tip-calculator.iam.gserviceaccount.com"
client_id = "110747729248681131610"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/pumpkins-tip-calculator%40pumpkins-tip-calculator.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

